version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10.15

commands:
  yarn_install:
    steps:
    - restore_cache:
        name: Restore Yarn Package Cache
        keys:
          - nuxt-jsonld-{{ checksum "yarn.lock" }}
    - run:
        name: Install Dependencies
        command: yarn install --frozen-lockfile
    - save_cache:
        name: Save Yarn Package Cache
        key: nuxt-jsonld-{{ checksum "yarn.lock" }}
        paths:
          - ~/.cache/yarn

jobs:
  lint:
    executor: node
    steps:
      - checkout
      - yarn_install
      - run: yarn lint

  test:
    executor: node
    steps:
      - checkout
      - yarn_install
      - run: yarn test:ci

  prepare_release:
    executor: node
    steps:
      - checkout
      - yarn_install
      - run:
          name: Prepare release
          command: |
            git config --global user.email "ryota.yama.9@gmail.com"
            git config --global user.name "ryota yamamoto"
            yarn release:prepare --yes --no-browse

  release:
    executor: node
    steps:
      - checkout
      - yarn_install
      - run: yarn release:trigger

workflows-references:
  hook-on-master: &hook-on-master
    filters:
      branches:
        only: master

workflows:
  version: 2
  test_and_release:
    jobs:
      - test
      - lint
      - prepare_release:
          <<: *hook-on-master
      - release:
          <<: *hook-on-master
          requires:
            - test
            - lint
            - prepare_release
